//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Content_Sharing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImgDB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ImgDB()
        {
            this.Comment = new HashSet<Comment>();
        }
    
        public int ImageID { get; set; }
        public int UserID { get; set; }
        public int ImgVote { get; set; }
        public string Name { get; set; }
        public string Route { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
